---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fatorial
  labels:
    app: fatorial
  annotations:
    federation.kubernetes.io/replica-set-preferences: {
        "rebalance": true,
        "clusters": {
          "gondor": {
            "weight": 1
          },
          "rivendell": {
            "weight": 0
          }
        }
      }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fatorial
  template:
    metadata:
      labels:
        app: fatorial
    spec:
      containers:
      - name: master
        image: vinhags/factorial-server
        command: ["python", "/code/app.py"]
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: fatorial
  labels:
    app: fatorial
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30666
  selector:
    app: fatorial
  type: NodePort
